# Generated by Django 4.1 on 2024-02-13 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameteroption',
            name='value',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
