# Generated by Django 5.0.2 on 2024-02-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_parameteroption_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='code',
            field=models.TextField(default='a', unique=True),
            preserve_default=False,
        ),
    ]
